# Generated by Django 5.2.8 on 2026-02-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=3000, null=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('item_description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('item_image', models.CharField(blank=True, max_length=3000, null=True)),
                ('quantity', models.IntegerField()),
                ('underrated_item', models.BooleanField(default=False, help_text='0-show, 1-hidden')),
                ('new_added_item', models.BooleanField(default=False, help_text='0-show, 1-hidden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.category')),
            ],
        ),
    ]
